--------------------------------------------------------
--  File created - Friday-July-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "N01304773"."CUSTOMERS" 
   (	"CUSTOMERID" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"BALANCE" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "S19ITE5220ONAGURDEEP" ;
REM INSERTING into N01304773.CUSTOMERS
SET DEFINE OFF;
Insert into N01304773.CUSTOMERS (CUSTOMERID,LASTNAME,FIRSTNAME,BALANCE) values ('customer2','Kent','Clark','40000.0');
Insert into N01304773.CUSTOMERS (CUSTOMERID,LASTNAME,FIRSTNAME,BALANCE) values ('customer','Bond','James','45000.0');
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "N01304773"."CUSTOMERS_PK" ON "N01304773"."CUSTOMERS" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "S19ITE5220ONAGURDEEP" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "N01304773"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "S19ITE5220ONAGURDEEP"  ENABLE;
  ALTER TABLE "N01304773"."CUSTOMERS" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "N01304773"."CUSTOMERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "N01304773"."CUSTOMERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "N01304773"."CUSTOMERS" MODIFY ("BALANCE" NOT NULL ENABLE);
